App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),

]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),

]

My_Ecommerce_Project/urls.py
from django.contrib import admin
from django.urls import path, include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls'))

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from typing import Any
from django.db import models

# To Create a Custom User Model and Admin Panel
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy

# To automatically create one to one objects
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class MyUserManager(BaseUserManager):
    """ A custom Manager to deal with emails as unique identifer """
    def _create_user(self, email, password, **extra_fields):
        """ Creates and saves a user with a given email and password"""
        if not email:
            raise ValueError("The Email must be set!")
        
        email = self.normalize_email(email)
        user = self.model(email=email,**extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser",True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True")
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(
        gettext_lazy("staff status"), 
        default=False, 
        help_text = gettext_lazy("Designates whether the user can log in this site")
    )
    is_active = models.BooleanField(
        gettext_lazy("active"),
        default=True,
        help_text = gettext_lazy("Designates whether this user should be treated as active. Unselect this instead of deleting accounts.")
    )

    USERNAME_FIELD = "email"
    objects = MyUserManager()

    def __str__(self):
        return self.email
    
    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=264, blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    address_1 = models.TextField(max_length=300, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username + "'s Profile"

    def is_fully_filled(self):
        fields_names = [f.name for f in self._meta.get_fields()]

        for field_name in fields_names:
            value = getattr(self, field_name)
            if value is None or value=='':
                return False
        return True


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

App_Login/forms.py
from django import forms
from django.forms import ModelForm
from App_Login.models import User, Profile
from django.contrib.auth.forms import UserCreationForm


# forms
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Email'}))
    password1 = forms.CharField(
        required = True,
        label = "",
        widget = forms.PasswordInput(attrs={'placeholder':'Password'})
    )
    password2 = forms.CharField(
        required = True,
        label = "",
        widget = forms.PasswordInput(attrs={'placeholder':'Password Confirmation'})
    )
    
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)



        

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse

# Authetication
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate

# Forms and Models
from App_Login.models import Profile
from App_Login.forms import ProfileForm, SignUpForm

# Messages
from django.contrib import messages


# Create your views here.

def sign_up(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account Created Successfully!")
            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/sign_up.html', context={'title':'Create New Account','form':form})


def login_user(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Shop:home'))
    return render(request, 'App_Login/login.html', context={'title':'Login','form':form})


@login_required
def logout_user(request):
    logout(request)
    messages.warning(request, "You are logged out!!")
    return HttpResponseRedirect(reverse('App_Shop:home'))


@login_required
def user_profile(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, "Change Saved!!")
            form = ProfileForm(instance=profile)
    return render(request, 'App_Login/change_profile.html', context={'title':'Profile','form':form})

templates/App_Login/change_profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title_block %} {{title}} {% endblock %}

{% block body_block %}

<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <br>
    <button type="submit" class="btn btn-warning btn-sm">Save</button>
</form>

<br>
<br>

{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title_block %} {{title}} {% endblock %}

{% block css_block %}
<style>
  .sign_up {
    width: 550px;
    border: 1px solid #ccc;
    padding: 25px;
  }
  .log_in {
    width: 550px;
    padding: 40px;
    border: 1px solid #ccc;
  }
</style>
{% endblock %}

{% block body_block %}
<center>

    <h2>Login</h2>

    <div class="log_in"> 
      <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <br>
        <button type="submit" class="btn btn-primary" style="width:100%">Log In</button>
      </form>
    </div>
    
    <br>
    
    <div class="sign_up">
      <p>Doesn't have an account? <a href="{% url 'App_Login:signup' %}" style="text-decoration: none;">Create New Account</a></p>
    </div>
    
</center>

{% endblock %}

templates/App_Login/sign_up.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title_block %} {{title}} {% endblock %}

{% block css_block %}
<style>
  .sign_up {
    width: 550px;
    border: 1px solid #ccc;
    padding: 40px;
  }
  .log_in {
    width: 550px;
    padding: 25px;
    border: 1px solid #ccc;
  }
</style>
{% endblock %}

{% block body_block %}
<center>

    <h2>Create New Account</h2>

    <div class='sign_up'>
      <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <br>
        <button type="submit" style="width:100%" class="btn btn-primary">Create Account</button>
      </form>
    </div>
    
    <br>
    
    <div class="log_in">
        <p>Already have an account? <a href="{% url 'App_Login:login' %}" style="text-decoration: none;">Login Here</a></p>
    </div> 
    
</center>
{% endblock %}



{% comment %} test_user@gmail.com || @UzXv6wM6MGy2Ya {% endcomment %}